language: python
python:
  - "3.7"
  - "3.8"
arch:
  - amd64
  - arm64
# enable docker in Travis
services:
  - docker
  
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+(-\S*)?$/
    - /^\d+\.\d+\.\d+(rc\d+)$/

# command to install dependencies
install:
  - if [ "${TRAVIS_CPU_ARCH}" == "arm64" ]; then
     sudo apt-get update;
     sudo chown -Rv $USER:$GROUP ~/.cache/pip/wheels;
     sudo apt-get install -y libffi-dev;
     sudo apt-get install -y libssl-dev;
     pip install cffi;
    fi
  - pip install tox tox-travis -U --force-reinstall

# command to run tests
script:
  - tox -vv
  - docker --version
  - make docs
  - make build
  - docker images
  - docker run `make version` --help

# push images to DockerHub and PyPI on tags
deploy:
  - provider: script
    script: bash build/docker_deploy.sh
    skip_cleanup: true
    on:
      tags: true
      python: "3.7"
      condition: -n "$DOCKER_PASSWORD"
  - provider: script
    script:  python -m pip install tox && tox -vve pypi_publish
    skip_cleanup: true
    on:
      tags: true
      python: "3.7"
      condition: -n "$TWINE_PASSWORD"
